version: '3.4'

services:
  kafka:
    image: confluentinc/cp-kafka

  zookeeper:
    image: confluentinc/cp-zookeeper

  connector:
    image: debezium/connect:latest

  paymentdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  payment.api:
    image: ${DOCKER_REGISTRY-}paymentapi
    build:
      context: .
      dockerfile: src/Payment.Api/Dockerfile
