version: '3.4'

services:
  zookeeper:
    container_name: zookeeper
    ports:
        - "2181:2181"
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181

  connector:
    container_name: connector
    ports:
        - "8083:8083"
    environment:
        GROUP_ID: 1
        CONFIG_STORAGE_TOPIC: my_connect_configs
        OFFSET_STORAGE_TOPIC: my_connect_offsets
        BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
        - zookeeper
        - paymentdb
        - kafka

  kafka:
    container_name: kafka
    ports:
        - "9092:9092"
    environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
        KAFKA_BROKER_ID: 1
        KAFKA_MIN_INSYNC_REPLICAS: 1
    depends_on:
        - zookeeper
        - paymentdb

  paymentdb:
    container_name: paymentdb
    environment:
        SA_PASSWORD: "ttt12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
  payment.api:
     container_name: payment.api
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "PaymentDbSettings:ConnectionStrings=Server=paymentdb;Database=PaymentDb;User Id=sa;Password=ttt12345678"  
     ports:
      - "8001:80"
     depends_on:
      - paymentdb
