version: '3.4'

services:
  paymentdb:
    container_name: paymentdb
    environment:
        SA_PASSWORD: "ttt12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
  payment.api:
     container_name: payment.api
     environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "PaymentDbSettings:ConnectionStrings=Server=paymentdb;Database=PaymentDb;User Id=sa;Password=ttt12345678"  
     ports:
      - "8001:80"
     depends_on:
      - paymentdb
